/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buccirenzettibragantimagazzino;

/**
 *
 * @author bucci.alex
 */
public class GUIMagazzino extends javax.swing.JFrame {

    /**
     * Creates new form GUIProdotto
     */
    public GUIMagazzino() {
        initComponents();
        this.setLocationRelativeTo(null); // null = centra sullo schermo
        file = new GestioneFile();
        tb = new Tabella(file);
        this.jTable2.setModel(tb);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnCompra = new javax.swing.JButton();
        btnVendi = new javax.swing.JButton();
        btnCerca = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magazzino");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(153, 153, 255)));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        BtnCompra.setText("Compra");
        BtnCompra.setBorder(null);
        BtnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCompraActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCompra);

        btnVendi.setText("Vendi");
        btnVendi.setBorder(null);
        btnVendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendiActionPerformed(evt);
            }
        });
        jPanel2.add(btnVendi);

        btnCerca.setText("🔍Cerca");
        btnCerca.setBorder(null);
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerca);

        btnElimina.setText("Elimina");
        btnElimina.setBorder(null);
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel2.add(btnElimina);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Nome ", "Prezzo ", "Prezzo Vendita", "Numero Disponibile", "Scorta Minima", "Numero Venduti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo che avviene quando premo il tasto compra
     *
     * @param evt evento onclick
     */
    private void BtnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCompraActionPerformed
        GUICompra f = new GUICompra(file, tb);
        f.setTitle("Compra Prodotto");
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setVisible(true);
        f.setLocationRelativeTo(this);

    }//GEN-LAST:event_BtnCompraActionPerformed

    /**
     * metodo che avviene quando premo il tasto vendi
     *
     * @param evt evento onclick
     */
    private void btnVendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendiActionPerformed
        GUIVendi f = new GUIVendi(file, tb);
        f.setTitle("Vendi Prodotto");
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setVisible(true);
        f.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnVendiActionPerformed

    /**
     * metodo che avviene quando premo il tasto cerca
     *
     * @param evt evento onclick
     */
    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        GUICerca f = new GUICerca();
        f.setTitle("Cerca Prodotto");
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setVisible(true);
        f.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnCercaActionPerformed

    /**
     * metodo che avviene quando premo il tasto elimina
     *
     * @param evt evento onclick
     */
    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        GUIelimina f = new GUIelimina(file, tb);
        f.setTitle("Elimina Prodotto");
        f.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        f.setVisible(true);
        f.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnEliminaActionPerformed
    /**
     * variabili globali
     */
    private GestioneFile file = new GestioneFile();
    private Tabella tb;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCompra;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnVendi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
